1. What is a Python library? Why do we use Python libraries?

In [ ]:
A Python library is a collection of pre-written code that provides specific functionalities, making it easier to perform 
common tasks without having to write the code from scratch. These libraries are modular, meaning you can import and use 
only the parts you need in your project.

Why Do We Use Python Libraries?
Reusability: Libraries offer reusable code, saving time and effort. Instead of reinventing the wheel, you can leverage existing, 
well-tested code.

Efficiency: Libraries are often optimized for performance. Using them can make your programs run faster and more efficiently.

Complex Tasks Simplified: Many libraries offer high-level abstractions that simplify complex tasks. For instance, libraries like NumPy 
simplify mathematical operations on large datasets, while Pandas streamlines data manipulation.

Community Support: Python libraries often have strong community support, including documentation, tutorials, and forums. This 
makes it easier to learn and troubleshoot issues.

Rapid Development: Libraries enable faster development by providing ready-to-use tools for various tasks, such as web development 
(Flask, Django), data analysis (Pandas, Matplotlib), and machine learning (TensorFlow, Scikit-learn).

Consistency: Libraries provide consistent interfaces and functions, which can make your code more readable and maintainable.


2. What is the difference between Numpy array and List?


In [ ]:
1. Data Type
NumPy Array: Designed specifically for numerical computation. All elements in a NumPy array must be of the same data type 
(e.g., all integers, all floats).
List: Can hold elements of different data types. You can have integers, floats, strings, and even other lists as elements 
within the same list.

2. Performance
NumPy Array: Much faster and more memory-efficient for numerical operations because they are implemented in C and optimized for performance. 
Operations on large datasets are significantly quicker.
List: Slower for numerical operations as they are more general-purpose and don't have the same level of optimization as NumPy arrays.

3. Functionality
NumPy Array: Supports advanced mathematical and statistical operations like element-wise addition, multiplication, and matrix operations. 
You can also use slicing, indexing, and broadcasting with NumPy arrays.
List: While you can perform some operations like addition or concatenation, lists don't natively support complex numerical operations or 
broadcasting. Lists are more suited for general data storage and manipulation.

4. Memory Efficiency
NumPy Array: More memory-efficient because they store data in a contiguous block of memory. This means less overhead compared to Python lists.
List: Less memory-efficient, especially when dealing with large datasets, because each element in a list is a Python object with associated 
overhead.

5. Dimensionality
NumPy Array: Supports multi-dimensional arrays (e.g., 2D matrices, 3D tensors) with ease, making it a powerful tool for scientific computing.
List: Typically used as a one-dimensional data structure, though you can create lists of lists to simulate multi-dimensional arrays. However, 
this is less efficient and more cumbersome than using NumPy arrays.

6. Operations
NumPy Array: Allows for vectorized operations, meaning you can perform operations on entire arrays at once without the need for explicit loops.
List: Operations typically require loops to process each element individually unless you use list comprehensions or other Python-specific 
techniques.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Find the shape, size, and dimension
shape = array.shape
size = array.size
dimension = array.ndim

shape, size, dimension


((3, 4), 12, 2)

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the first row
first_row = array[0]

first_row


array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = array[2, 3]

element


12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Flatten the array to 1D and extract odd-indexed elements
odd_indexed_elements = array.flatten()[1::2]

odd_indexed_elements


array([ 2,  4,  6,  8, 10, 12])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

random_matrix


array([[0.68316516, 0.27541353, 0.53900002],
       [0.82557003, 0.72292386, 0.51121096],
       [0.44913836, 0.22323125, 0.03511533]])

8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
'''1. np.random.rand
Purpose: Generates random numbers from a uniform distribution.

Range: The numbers are uniformly distributed between 0 and 1 (exclusive of 1).

Syntax: np.random.rand(d0, d1, ..., dn)
Generates a random array of shape (d0, d1, ..., dn).

2. np.random.randn
Purpose: Generates random numbers from a standard normal distribution (also known as a Gaussian distribution).

Range: The numbers are drawn from a distribution with a mean of 0 and a standard deviation of 1.

Syntax: np.random.randn(d0, d1, ..., dn)
Generates a random array of shape (d0, d1, ..., dn). '''

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [7]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Increase the dimension of the array
expanded_array = np.expand_dims(array, axis=0)

expanded_array


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Transpose the array using .T
transposed_array = array.T

# Alternatively, use np.transpose()
# transposed_array = np.transpose(array)

transposed_array


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
(1) Index wise multiplicatio
(2) Matrix multiplicatio
(3) Add both the matric

(4) Subtract matrix B from A 
(5) Divide Matrix B by A

In [10]:
import numpy as np

# Define the matrices
matrix_a = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

matrix_b = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# (1) Index wise multiplication
index_wise_multiplication = matrix_a * matrix_b

# (2) Matrix multiplication
# For matrix multiplication, matrix B needs to be transposed
matrix_multiplication = np.dot(matrix_a, matrix_b.T)

# (3) Add both matrices
matrix_addition = matrix_a + matrix_b

# (4) Subtract matrix B from A
matrix_subtraction = matrix_a - matrix_b

# (5) Divide Matrix B by A
# Ensure no division by zero; here, both matrices have no zero values
matrix_division = matrix_b / matrix_a

# Output results
index_wise_multiplication, matrix_multiplication, matrix_addition, matrix_subtraction, matrix_division


(array([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]]),
 array([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

12. Which function in Numpy can be used to swap the byte order of an array?

In [ ]:
'''In NumPy, you can use the byteswap() function to swap the byte order of an array. This function is used to reverse the 
byte order of the array elements, which can be useful when dealing with different endian formats.'''

13. What is the significance of the np.linalg.inv function?

In [ ]:
'''In Python, the numpy library provides a convenient function, np. linalg. inv(), for calculating the inverse of a matrix efficiently. 
Check out this numpy code example to explore how to inverse a matrix in Python using np.'''

14. What does the np.reshape function do, and how is it used?

In [ ]:
'''The np.reshape function in NumPy is used to change the shape of an existing array without changing its data. It allows you 
to specify a new shape for the array while keeping the total number of elements the same.

Function Signature:
numpy.reshape(a, newshape, order='C')

Parameters:
a: The input array you want to reshape.
newshape: The desired shape of the output array. This can be specified as a tuple (e.g., (rows, columns)) or as a single integer 
(e.g., n), in which case the array will be reshaped to a 1D array with n elements.
order (optional): Specifies the order in which elements are read from the array. 'C' is for row-major (C-style) order, 
and 'F' is for column-major (Fortran-style) order. The default is 'C'.
'''



15. What is broadcasting in Numpy?

In [ ]:
'''Broadcasting in NumPy is a powerful concept that allows you to perform operations on arrays of different shapes and sizes in 
a way that is both efficient and intuitive. It essentially enables NumPy to perform element-wise operations on arrays that do 
not have the same shape by automatically expanding the smaller array to match the shape of the larger array.'''

